// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel FunctionKernel

RWStructuredBuffer<float3> myPositions, myScale, myVelocity;
RWStructuredBuffer<float4> myColor;
RWStructuredBuffer<float> myLifeTime;
float deltaTime;


[numthreads(512,1,1)]
void FunctionKernel (uint3 id : SV_DispatchThreadID)
{
	myPositions[id.x] = myPositions[id.x] + myVelocity[id.x] * deltaTime;
}